import enum


class DeviceType(enum.Enum):

    LUA = "LUA"
    VIRTUAL_UCM = "VIRTUAL_UCM"
    HARDWARE_UCM = "HARDWARE_UCM"
    STANDALONE = "STANDALONE"
    GATEWAY = "GATEWAY"
    LINK_MASTER_UCM = "LINK_MASTER_UCM"
    LINK_SLAVE_UCM = "LINK_SLAVE_UCM"
    EMBEDDED_UCM = "EMBEDDED_UCM"
    NATIVE = "NATIVE"
