version: "3"
services:
  snmp-eaton-ups-ucm:
    build: .
    image: enapter-vucm-examples/snmp-eaton-ups:latest
    stop_signal: SIGINT
    environment:
      ENAPTER_VUCM_BLOB: "REALENAPTERVUCMBLOBMUSTBEHERE="
      ENAPTER_SNMP_HOST: "192.168.192.192"
      ENAPTER_SNMP_PORT: "161"
      ENAPTER_SNMP_COMMUNITY: "public"
