name: Publish

on:
  push:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Install pipenv
        run: make get-pipenv

      - name: Install dependencies
        run: make install-deps

      - name: Publish to Test PyPI
        run: make upload-to-test-pypi
        env:
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        run: make upload-to-pypi
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
