name: Publish

on:
  push:
    tags:
      - v*

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: make get-pipenv

      - name: Install dependencies
        run: make install-deps

      - name: Publish to PyPI
        run: make upload-to-pypi
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
